[tool.poetry]
name = "eda"
version = "0.1.0"
description = ""
authors = ["wnc6 <wchew013@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
ipykernel = "^6.29.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
